name = "Sutton, Epsom and Wimbledon"
description = "A simulation of commuter routes in South-West London"
display_name = "Sutton, Epsom and Wimbledon"
country_code = "GB"
rly_file = "SuttonEpsomWimbledon.rly"
ttb_files = [ "SWE-LondonVictoriaClosure.ttb",]
ssn_files = []
doc_files = [ "README.pdf",]
img_files = [ "SuttonEpsomWimbledon.bmp",]
year = 2021
factual = true
difficulty = 3
author = "Daniel Gill"
contributors = []
version = "1.0.0"
release_date = ""
